# Generated by Django 4.2.13 on 2026-08-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Name')),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField()),
                ('mobile_no', models.CharField(max_length=20, verbose_name='Mobile No')),
                ('software_requirement', models.TextField(verbose_name='S/W Requirement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Demo Enquiry',
                'verbose_name_plural': 'Demo Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
